<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVQ6dHJx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVQ6dHJx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVQ6dHJx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVQ6dHJx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVQ6dHJx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VQ6dHJx',
    'container.build_id' => '7bf2dd3d',
    'container.build_time' => 1517320322,
));
